# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    PIP_CACHE_DIR: $(Pipeline.Workspace)/.pip

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- task: Cache@2
  inputs:
    key: 'python | "$(Agent.OS)" | requirements.txt'
    restoreKeys: | 
      python | "$(Agent.OS)"
      python
    path: $(PIP_CACHE_DIR)
  displayName: 'Cache pip packages'

- script: |
    python -m pip install --upgrade pip
    pip install pytest-azurepipelines
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest --junitxml=junit/test-results.xml --cov-report=xml --cov=src tests/
  displayName: 'pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    failTaskOnFailedTests: true
    testResultsFiles: 'junit/test-results.xml'
    testRunTitle: 'pytest-coverage'
  displayName: 'Publish test results'