name: CI

on:
  push:
    branches: 
      - feature/blackcheck

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: check code format
      run: | 
        pip install black
        sh scripts/check-format.sh 81 .
      if: always()

