name: CI

on:
  push:
    branches: 
      - master
  pr:
    branches:
      - master

jobs:
  check-code-format:
    name: check-code-format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.7'
        architecture: 'x64'

    - name: Check code format
      run: | 
        python -m pip install --upgrade pip
        pip install black
        sh scripts/check-format.sh 81 .
      if: always()

