name: CI

on:
  push:
    branches: 
      - feature/blackcheck

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: check code format
    - uses: actions/setup-python@v2
      with: 
        python-version: '3.7'
        architecture: 'x64'
      run: | 
        python -m pip install --upgrade pip
        pip install black
        sh scripts/check-format.sh 81 .
      if: always()

